import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-primary">
        <button onClick={() => console.log("clicked")}>Click me</button>
      </main>
    </div>
  );
};

export default Home;
